services:
  - type: web
    plan: free
    name: pex-agreements
    env: docker
    autoDeploy: false
    repo: https://github.com/Project-Exoduss/agreements
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pex-agreements-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
    buildCommand: |
      # Clean and verify dependencies
      rm -rf node_modules yarn.lock
      # Install specific version of shakapacker
      yarn add shakapacker@8.0.2 --exact
      # Install other dependencies
      yarn install --frozen-lockfile --network-timeout 600000
      # Verify shakapacker version
      yarn list shakapacker
      # Build webpack assets
      yarn run webpack --config config/webpack/webpack.config.js --mode=production
      # Precompile assets (after webpack build)
      bundle exec rake assets:precompile RAILS_ENV=production NODE_ENV=production
      # Run migrations
      bundle exec rake db:migrate
databases:
  - name: pex-agreements-db
    plan: free