services:
  - type: web
    plan: free
    name: pex-agreements
    env: docker
    autoDeploy: false
    repo: https://github.com/Project-Exoduss/agreements
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pex-agreements-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
    buildCommand: |
      # Install yarn dependencies
      yarn install --frozen-lockfile --network-timeout 600000
      # Precompile assets
      bundle exec rake assets:precompile RAILS_ENV=production NODE_ENV=production
      # Run migrations
      bundle exec rake db:migrate
databases:
  - name: pex-agreements-db
    plan: free