services:
  - type: web
    plan: free
    name: pex-agreements
    env: docker
    autoDeploy: false
    repo: https://github.com/Project-Exoduss/agreements
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pex-agreements-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
    buildCommand: |
      yarn install
      bundle exec rake assets:precompile
      bundle exec rake db:migrate
databases:
  - name: pex-agreements-db
    plan: free