services:
  - type: web
    plan: free
    name: pex-agreements
    env: docker
    autoDeploy: false
    repo: https://github.com/Project-Exoduss/agreements
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pex-agreements-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
databases:
  - name: pex-agreements-db
    plan: free